version: '3.1'

services:
  db:
    ports: 
      - "5432:5432"
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: matomo
      POSTGRES_USER: matomo
      POSTGRES_DB: matomo