version: '3.1'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: annual
      POSTGRES_USER: annual
      POSTGRES_DB: annual
