name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        directory:
          - matomo
          - notification-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use the reusable workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          directory: ${{ matrix.directory }}
