name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

jobs:
  test:
    uses: ./.github/workflows/reusable-workflow.yml
    strategy:
      matrix:
        directory:
          - matomo
          - notification-service
    with:
      ref: ${{ matrix.directory }}
