name: Build and export image

on:
  push:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Test
        run: pip install poetry && poetry install && poetry run pytest

      - name: Build and export
        id: build
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6.1.0
        with:
          platforms: linux/amd64,linux/arm64
          image: cern-sis/library-notifications-service
          registry: registry.cern.ch
          cache: false
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Deploy with new image
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.1.0
        with:
          event-type: update
          images: ${{ steps.build.outputs.image-tags }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
