name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

jobs:
  test:
    uses: ./.github/workflows/tests.yaml
    with:
      directory: ${{ matrix.directory }}
    strategy:
      matrix:
        directory:
          - matomo-api
          - Library-Notification-Service
  release:
    uses: ./.github/workflows/release.yaml
    with:
      directory: ${{ matrix.directory }}
      image-name: ${{ matrix.image-name }}
    strategy:
      matrix:
        directory:
          - matomo-api
          - Library-Notification-Service
        image-name:
          - cern-sis/matomo-api
          - cern-sis/library-notifications-service
