name: Test

on:
  push:
    branches:
    - main

jobs:
  test:
    uses: ./.github/workflows/tests.yaml
    with:
      directory: ${{ matrix.directory }}
    strategy:
      matrix:
        directory:
          - matomo-api
          - Library-Notification-Service
  release:
    uses: ./.github/workflows/release.yaml
    with:
      directory: ${{ matrix.directory }}
      image-name: ${{ matrix.image-name }}
    secrets: inherit
    strategy:
      matrix:
        include:
          - directory: matomo-api
            image-name: cern-sis/matomo-api
          - directory: Library-Notification-Service
            image-name: cern-sis/library-notifications-service
